# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_binary_packages:
  - devtools
  - roxygen2

after_success:
  - Rscript -e 'devtools::install()'
  - Rscript -e 'devtools::test()'
  - Rscript -e 'covr::report()'
