# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

sudo: false
cache: packages

os:
  - linux

language: r
r:
  - oldrel
  - release
  - devel

matrix:
  fast_finish: true
  allow_failures:
  - r: oldrel

r_binary_packages:
  - devtools
  - roxygen2
  - covr
  - purrr

after_success:
  - Rscript -e 'devtools::install()'
  - Rscript -e 'devtools::test()'
  - Rscript -e 'covr::package_coverage(type = "all",combine_types = FALSE)'
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
