# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

sudo: false
cache: packages
language: r
r:
  - oldrel
  - release
  - devel

r_binary_packages:
  - devtools
  - roxygen2
  - covr

after_success:
  - Rscript -e 'devtools::install()'
  - Rscript -e 'devtools::test()'
  - Rscript -e 'covr::report()'
